### ISSUE TITLE
Docker 18.06.0+ and docker-compose.yml upgrade

### ISSUE THREAD

**Issue by berehovskyi** [forcedotcom/RecordViewer#52]
It should be mentioned that once you use the current version of the `docker-compose.yml` file together with Docker 18.06.0+ you may encounter a problem with compatibility.  You can fix it by explicitly adding 2 sections:
```
version: '2.1'
services:

  web:
    build: .
    command: 'bash -c ''node app.js'''
    working_dir: /usr/src/app
    environment:
      PORT: 8050
      NGINX_PORT: 8443
    volumes:
      - './views:/app/user/views:ro'
  nginx:
    build: nginx
    ports:
      - '8080:80'
      - '8443:443'
    links:
      - web:web
    volumes_from:
      - web
```
